async function createPcmToOggModule(moduleArg={}){var moduleRtn;var b=moduleArg,g=!!globalThis.window,h=!!globalThis.WorkerGlobalScope,k=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(k){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var l=(a,c)=>{throw c;},m=import.meta.url,n="",p,q;
if(k){var fs=require("fs");m.startsWith("file:")&&(n=require("path").dirname(require("url").fileURLToPath(m))+"/");q=a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a)};p=async a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);l=(a,c)=>{process.exitCode=a;throw c;}}else if(g||h){try{n=(new URL(".",m)).href}catch{}h&&(q=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)});p=async a=>{if(r(a))return new Promise((d,
e)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?d(f.response):e(f.status)};f.onerror=e;f.send(null)});var c=await fetch(a,{credentials:"same-origin"});if(c.ok)return c.arrayBuffer();throw Error(c.status+" : "+c.url);}}console.log.bind(console);var t=console.error.bind(console),u,v=!1,r=a=>a.startsWith("file://"),w,x,y,z=!1;
function A(){var a=B.buffer;new Int8Array(a);new Int16Array(a);b.HEAPU8=y=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);new Uint32Array(a);b.HEAPF32=new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}var C;async function D(a){if(!u)try{var c=await p(a);return new Uint8Array(c)}catch{}if(a==C&&u)a=new Uint8Array(u);else if(q)a=q(a);else throw"both async and sync fetching of the wasm failed";return a}
async function E(a,c){try{var d=await D(a);return await WebAssembly.instantiate(d,c)}catch(e){throw t(`failed to asynchronously prepare wasm: ${e}`),a=e,b.onAbort?.(a),a="Aborted("+a+")",t(a),v=!0,a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info."),x?.(a),a;}}
async function F(a){var c=C;if(!u&&!r(c)&&!k)try{var d=fetch(c,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(e){t(`wasm streaming compile failed: ${e}`),t("falling back to ArrayBuffer instantiation")}return E(c,a)}class G{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var H=a=>{for(;0<a.length;)a.shift()(b)},I=[],J=[],K=()=>{var a=b.preRun.shift();J.push(a)},L=!0;b.noExitRuntime&&(L=b.noExitRuntime);
b.printErr&&(t=b.printErr);b.wasmBinary&&(u=b.wasmBinary);if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.shift()();
var B,M={b:()=>Date.now(),a:a=>{var c=y.length;a>>>=0;if(2147483648<a)return!1;for(var d=1;4>=d;d*=2){var e=c*(1+.2/d);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(e);A();var f=1;break a}catch(O){}f=void 0}if(f)return!0}return!1},c:a=>{L||(b.onExit?.(a),v=!0);l(a,new G(a))}},N;
N=await (async function(){function a(d){d=N=d.exports;b._malloc=d.f;b._free=d.g;b._encode_pcm_to_ogg=d.h;b._get_ogg_output_data=d.i;b._get_ogg_output_size=d.j;b._free_ogg_output=d.k;B=d.d;A();return N}var c={a:M};if(b.instantiateWasm)return new Promise(d=>{b.instantiateWasm(c,(e,f)=>{d(a(e,f))})});C??=b.locateFile?b.locateFile?b.locateFile("pcm_to_ogg.wasm",n):n+"pcm_to_ogg.wasm":(new URL("pcm_to_ogg.wasm",import.meta.url)).href;return a((await F(c)).instance)}());
(function(){function a(){b.calledRun=!0;if(!v){z=!0;N.e();w?.(b);b.onRuntimeInitialized?.();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();I.push(c)}H(I)}}if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)K();H(J);b.setStatus?(b.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>b.setStatus(""),1);a()},1)):a()})();z?moduleRtn=b:moduleRtn=new Promise((a,c)=>{w=a;x=c});
;return moduleRtn}export default createPcmToOggModule;
